FROM python:3.9
 
# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install curl and other necessary dependencies
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl -fSsL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /usr/share/keyrings/google-chrome.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y google-chrome-stable && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

COPY . /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install Python packages
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "scrap_daily_detail.py"]
